---

- name: Install HAproxy 2.4 Centos
  block:
    - name: Centos - Prepare to install haproxy 2.4
      shell: |
        cd /opt
        git clone https://github.com/DBezemer/rpm-haproxy.git 
        cd ./rpm-haproxy
        git checkout 2.4
    - name: Centos - Compile and install
      shell: |
        cd /opt/rpm-haproxy
        make
        rpm -U /opt/rpm-haproxy/rpmbuild/RPMS/x86_64/haproxy-2.4.17-1.el7.x86_64.rpm
    - name: Centos - copy haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
    - name: Centos - Start and enable haproxy daemon
      service:
        name: haproxy
        state: started
        enabled: yes
  when: ansible_distribution == "CentOS"

- name: Replace master_ip in /etc/kubernetes/kubelet.conf
  replace:
    path: /etc/kubernetes/kubelet.conf
    regexp: '^(.+server:.+)$'
    replace: '    server: https://127.0.0.1:6443'

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

- name: Restart docker
  service:
    name: docker
    state: restarted
