
#- name: Test hosts list
#  debug:
#    msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Create dirs
  file:
    path: /opt/archives
    state: directory

- name: Get etcd archive
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{etcd_version}}/etcd-{{etcd_version}}-linux-amd64.tar.gz
    dest: /opt/archives/etcd-{{etcd_version}}-linux-amd64.tar.gz

- name: Get and unpack etcd
  shell: |
    tar -xvf etcd-{{etcd_version}}-linux-amd64.tar.gz -C /usr/local/bin/ --strip-components=1
  args:
    chdir: /opt/archives

- name: Create systemd service for etcd
  template:
    src: etcd.service.j2
    dest: "/etc/systemd/system/etcd.service"

- name: Create etcd env file
  template:
    src: etcd.env.j2
    dest: /etc/etcd.env

- name: Enable and start etc cluster
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes

- name: Check member list cluster
  shell: /usr/local/bin/etcdctl member list
  register: etcd_member

- name: Etcd member status
  debug:
    msg: "{{etcd_member.stdout}}"

- name: Check etcd health
  shell: /usr/local/bin/etcdctl endpoint health --cluster
  register: etcd_health

- name: Etcd health
  debug:
    msg: "{{etcd_health.stdout}}"
    