---

  - name: Remove masters from inventory
    lineinfile:
      path: "{{inventory_file}}"
      state: absent
      regexp: '^master.*'
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Remove workers from inventory
    lineinfile:
      path: "{{inventory_file}}"
      state: absent
      regexp: '^worker.*'
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Remove join token from inventory
    lineinfile:
      path: "{{inventory_file}}"
      state: absent
      regexp: '^k8s_join.*'
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Destroy plan
    shell: |
      export TF_CLI_CONFIG_FILE='/etc/terraform/.terraformrc'
      cd {{k8s_project_dir}}/
      terraform destroy -auto-approve -no-color

