---

  - name: Copy infrastructure plan
    template:
      src: k8s.tf.j2
      dest: "{{k8s_project_dir}}/k8s.tf"

  - name: Copy user metadata
    template:
      src: meta.txt.j2
      dest: "{{k8s_project_dir}}/meta.txt"

  - name: Apply plan
    shell: |
      export TF_CLI_CONFIG_FILE='/etc/terraform/.terraformrc'
      cd {{k8s_project_dir}}/
      terraform apply -auto-approve -no-color

  - name: Get info about instances
    shell: |
      cd {{k8s_project_dir}}/
      terraform output -json
    register: k8s_plan_json

#  - name: Output -json
#    debug:
#      msg: "--> {{item}}"
#    loop: "{{(k8s_plan_json.stdout | from_json).external_ips.value}}"

  - name: Add new masters to inventory
    lineinfile:
      path: "{{inventory_file}}"
      line: "{{item[:-1]}}"
      insertafter: \[k8s_master\].*
    loop: "{{(k8s_plan_json.stdout | from_json).fqdn_master.value}}"
    loop_control:
      index_var: i
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Add new workers to inventory
    lineinfile:
      path: "{{inventory_file}}"
      line: "{{item[:-1]}}"
      insertafter: \[k8s_worker\].*
    loop: "{{(k8s_plan_json.stdout | from_json).fqdn_worker.value}}"
    loop_control:
      index_var: i
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Append ansible_host for masters in inventory
    replace:
      path: "{{inventory_file}}"
      regexp: '^(master{{i}}.+)$'
      replace: '\1 {{"ansible_host="+item}}'
    loop: "{{(k8s_plan_json.stdout | from_json).nat_ip_master.value}}"
    loop_control:
      index_var: i
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Append ansible_host for workers in inventory
    replace:
      path: "{{inventory_file}}"
      regexp: '^(worker{{i}}.+)$'
      replace: '\1 {{"ansible_host="+item}}'
    loop: "{{(k8s_plan_json.stdout | from_json).nat_ip_worker.value}}"
    loop_control:
      index_var: i
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Append ansible_priv_ip for masters in inventory
    replace:
      path: "{{inventory_file}}"
      regexp: '^(master{{i}}.+)$'
      replace: '\1 {{"ansible_priv_ip="+item}}'
    loop: "{{(k8s_plan_json.stdout | from_json).ip_master.value}}"
    loop_control:
      index_var: i
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

  - name: Append ansible_priv_ip for workers in inventory
    replace:
      path: "{{inventory_file}}"
      regexp: '^(worker{{i}}.+)$'
      replace: '\1 {{"ansible_priv_ip="+item}}'
    loop: "{{(k8s_plan_json.stdout | from_json).ip_worker.value}}"
    loop_control:
      index_var: i
    delegate_to: 127.0.0.1
    become: true
    become_user: "{{localhost_localuser}}"

#  - name: Add new masters to inventory
#    lineinfile:
#      path: "{{inventory_file}}"
#      line: "master{{i}}-{{tf_cloud_id}} ansible_host={{item}}"
#      insertafter: \[k8s_master\].*
#    loop: "{{(k8s_plan_json.stdout | from_json).ip_master.value}}"
#    loop_control:
#      index_var: i
#    delegate_to: 127.0.0.1
#    become: true
#    become_user: "{{localhost_localuser}}"

#  - name: Add new nodes to inventory
#    lineinfile:
#      path: "{{inventory_file}}"
#      line: "node{{i}}-{{tf_cloud_id}} ansible_host={{item}}"
#      insertafter: \[k8s_node\].*
#    loop: "{{(k8s_plan_json.stdout | from_json).ip_node.value}}"
#    loop_control:
#      index_var: i
#    delegate_to: 127.0.0.1
#    become: true
#    become_user: "{{localhost_localuser}}"

#  - name: Append external ip to masters in inventory
#    replace:
#      path: "{{inventory_file}}"
#      regexp: '^(master{{i}}.+)$'
#      replace: '\1 {{"ansible_natip="+item}}'
#    loop: "{{(k8s_plan_json.stdout | from_json).nat_ip_master.value}}"
#    loop_control:
#      index_var: i
#    delegate_to: 127.0.0.1
#    become: true
#    become_user: "{{localhost_localuser}}"

#  - name: Add hosts to inventory
#    add_host:
#      name: "master{{i}}"
#      groups: "k8s_master"
#      ansible_host: "{{item}}"
#    loop: "{{(k8s_plan_json.stdout | from_json).external_ips.value}}"
#    loop_control:
#      index_var: i
