---

 - hosts: terraform
   gather_facts: false
   roles:
     - '10-install-terraform-1.1.9'
     - '10-k8s-build-infrastructure'
   tasks:
     - meta: refresh_inventory

 - hosts: k8s_master
   gather_facts: false
   tasks:
     - name: Wait for VMs
       wait_for_connection:

 - hosts: k8s_master
   gather_facts: true
   roles:
     - '20-k8s-install-kubetools'
     - '90-install-docker'
     - '90-install-etcd'
     - '20-k8s-init-cluster'

 - hosts: k8s_worker
   gather_facts: true
   roles:
     - '20-k8s-install-kubetools'
     - '90-install-docker'
     - '20-k8s-join-workers'
     - '20-k8s-install-haproxy'

 - hosts: k8s_master
   gather_facts: true
   roles:
     - '20-k8s-ingress-nginx'
